name: My brand CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
    
env:
  MONGOURI: ${{secrets.MONGOURI}}
  PORT: ${{secrets.PORT}}
  CLOUD_NAME: ${{secrets.CLOUD_NAME}}
  API_KEY: ${{secrets.API_KEY}}
  API_SECRET: ${{secrets.API_SECRET}}
  JWT_SECRET: ${{secrets.JWT_SECRET}}
  DB_PASSWORD: ${{secrets.DB_PASSWORD}}
 

  
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci 
    - run: npm test    
    - run: npm run build --if-present
      
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

        slug: Jovz19200/My-Brand-BE

